=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/pub-stomp/pub_stomp_adapter_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:p="pub_stomp_adapter_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="pub_stomp_adapter_v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pub_stomp_adapter_v1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="subscriptors">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="subscriptor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:unsignedByte" />
                    <xs:element name="enabled" type="xs:boolean" />
                    <xs:element name="entity" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="publishers">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="publisher">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:unsignedByte" />
                    <xs:element name="enabled" type="xs:boolean" />
                    <xs:element name="broker" type="xs:string" />
                    <xs:element name="user" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="password" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="topics">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="topic">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="id" type="xs:unsignedByte" />
                                <xs:element name="enabled" type="xs:boolean" />
                                <xs:element name="entity" type="xs:string" />
                                <xs:element name="publisher_class" type="xs:string" />
                                <xs:element name="merge_wait_time" type="xs:long" />
                                <xs:element name="subscriptors_ref">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="subscriptor_id_ref" type="xs:unsignedByte" />
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="custom_path" type="xs:boolean" />
                                <xs:element name="path" type="xs:string" minOccurs="0" maxOccurs="1" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SCADA-ITS/configscada/rits/resources/master/adapters/pub-stomp/pub_stomp_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:pub_stomp_adapter_v1 name="" version=""
	xmlns:p="pub_stomp_adapter_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="pub_stomp_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/pub-stomp/pub_stomp_adapter_v1.xsd ">
	<p:subscriptors>
		<p:subscriptor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetElementValuesPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>2</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetElementStatesPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>3</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetAlarmsPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>4</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetPlanStatePublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>6</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetGenericData</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>7</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetIncidentReportsPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>8</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetPlanSchedulesPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>9</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetPlanSchedulesStatePublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>10</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetExIncidentPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>11</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetAuditLogPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>12</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetBlockIncidentReportsPublishCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>13</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetPmQueuePublishCommand</p:entity>
		</p:subscriptor>
	</p:subscriptors>
	<p:publishers>
		<p:publisher>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:broker>ws://192.168.88.80:61614</p:broker>
			<p:topics>
				<p:topic>
					<p:id>2</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>AlarmVO</p:entity>
					<p:publisher_class>AlarmPublisher</p:publisher_class>
					<p:merge_wait_time>500</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>3</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>true</p:custom_path>
					<!--<p:path>/topic/alarm</p:path> -->
				</p:topic>
				<p:topic>
					<p:id>3</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>PlanVO</p:entity>
					<p:publisher_class>PlanPublisher</p:publisher_class>
					<p:merge_wait_time>500</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>4</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>false</p:custom_path>
					<p:path>/topic/plan.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>4</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>PlanSchedulesVO</p:entity>
					<p:publisher_class>PlanSchedulesPublisher</p:publisher_class>
					<p:merge_wait_time>1</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>8</p:subscriptor_id_ref>
						<p:subscriptor_id_ref>9</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>false</p:custom_path>
					<p:path>/topic/planSchedules.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>6</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>GenericDataVO</p:entity>
					<p:publisher_class>GenericDataPublisher</p:publisher_class>
					<p:merge_wait_time>1</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>6</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>false</p:custom_path>
					<p:path>/topic/generic_data.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>7</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>ImsIncidentReportVO</p:entity>
					<p:publisher_class>IncidentPublisher</p:publisher_class>
					<p:merge_wait_time>2000</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>7</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>false</p:custom_path>
					<p:path>/topic/incidentReport.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>8</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>ImsExtIncidentVO</p:entity>
					<p:publisher_class>ExtIncidentPublisher</p:publisher_class>
					<p:merge_wait_time>500</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>10</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>true</p:custom_path>
					<p:path>/topic/extIncident.{extIncidentTypeId}.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>9</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>ElementVO</p:entity>
					<p:publisher_class>ElementByElementTypePublisher</p:publisher_class>
					<p:merge_wait_time>500</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>1</p:subscriptor_id_ref>
						<p:subscriptor_id_ref>2</p:subscriptor_id_ref>
						<p:subscriptor_id_ref>3</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>true</p:custom_path>
					<p:path>/topic/element.{elementTypeId}.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>10</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>AuditLogVO</p:entity>
					<p:publisher_class>AuditLogPublisher</p:publisher_class>
					<p:merge_wait_time>1000</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>11</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>true</p:custom_path>
					<p:path>/topic/auditLog.{logTypeId}</p:path>
				</p:topic>
				<p:topic>
					<p:id>11</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>ImsIncidentReportVO</p:entity>
					<p:publisher_class>BlockIncidentPublisher</p:publisher_class>
					<p:merge_wait_time>1</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>12</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>false</p:custom_path>
					<p:path>/topic/incidentReport.{id}</p:path>
				</p:topic>
				<p:topic>
					<p:id>12</p:id>
					<p:enabled>true</p:enabled>
					<p:entity>ElementVO</p:entity>
					<p:publisher_class>PmQueuePublisher</p:publisher_class>
					<p:merge_wait_time>500</p:merge_wait_time>
					<p:subscriptors_ref>
						<p:subscriptor_id_ref>13</p:subscriptor_id_ref>
					</p:subscriptors_ref>
					<p:custom_path>false</p:custom_path>
					<p:path>/topic/pm_queue.{id}</p:path>
				</p:topic>
			</p:topics>
		</p:publisher>
	</p:publishers>
</p:pub_stomp_adapter_v1>
