=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:p="json_generic_mango_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="json_generic_mango_v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="json_generic_mango_v1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="groovy_adapter" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:attribute name="file" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      	<xs:element name="session_uid">
          <xs:complexType>
            <xs:attribute name="element_type_param_id" type="xs:long" use="required" />
            <xs:attribute name="param_type_id" type="xs:long" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="state">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="state_value">
                <xs:complexType>
                  <xs:attribute name="source" type="xs:long" use="required" />
                  <xs:attribute name="input" type="xs:long" use="required" />
                  <xs:attribute name="disconnected" type="xs:boolean" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="field" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="fields" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="field">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="source" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="input" minOccurs="0" maxOccurs="1" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="element_type_param_id" type="xs:long" />
                          <xs:element name="param_type_id" type="xs:long" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="use_adapter" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="alarms" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="alarm">
                <xs:complexType>
                  <xs:attribute name="source" type="xs:string" use="required" />
                  <xs:attribute name="active_value" type="xs:string" use="required" />
                  <xs:attribute name="alarm_config_id" type="xs:long" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
      <xs:attribute name="element_type_id" type="xs:long" use="required" />
      <xs:attribute name="array_element_id" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/maqueta_p_industrial/adapters/mango/03_detector_etd.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="3">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:alarms>
        <p:alarm source="fail_data" active_value="true" alarm_config_id="040001"></p:alarm>
        <p:alarm source="congestion" active_value="true" alarm_config_id="040003"></p:alarm>
  </p:alarms>
    
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/rits/resources/project/avo/adapters/mango/09_axialfan.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
  xmlns:p="json_generic_mango_v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " 
    element_type_id="9" array_element_id="2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435" >
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>fan_state</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>fan_vibration</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>front_bearing_temperature</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>back_bearing_temperature</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>fan_available</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>flow</p:source>
      <p:input>
        <p:element_type_param_id>8</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>parcial_operating_hours</p:source>
      <p:input>
        <p:element_type_param_id>14</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>total_operating_hours</p:source>
      <p:input>
        <p:element_type_param_id>15</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>power</p:source>
      <p:input>
        <p:element_type_param_id>16</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>engine_reference</p:source>
      <p:input>
        <p:element_type_param_id>17</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>engine_speed</p:source>
      <p:input>
        <p:element_type_param_id>18</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>engine_speed_rpm</p:source>
      <p:input>
        <p:element_type_param_id>19</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>axial_direct_order</p:source>
      <p:input>
        <p:element_type_param_id>20</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>axial_reverse_order</p:source>
      <p:input>
        <p:element_type_param_id>21</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>local_mode</p:source>
      <p:input>
        <p:element_type_param_id>22</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>remote_mode</p:source>
      <p:input>
        <p:element_type_param_id>23</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>emergency_mode</p:source>
      <p:input>
        <p:element_type_param_id>24</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>opened_damper</p:source>
      <p:input>
        <p:element_type_param_id>25</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>closed_damper</p:source>
      <p:input>
        <p:element_type_param_id>26</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>n_starts</p:source>
      <p:input>
        <p:element_type_param_id>27</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
    <p:alarms>
    <p:alarm source="present_trip" active_value="true" alarm_config_id="090010"></p:alarm>
    <p:alarm source="emergency_button_pushed" active_value="true" alarm_config_id="090011"></p:alarm>
    <p:alarm source="variator_fail" active_value="true" alarm_config_id="090012"></p:alarm>
    <p:alarm source="running_timeout_exceeded" active_value="true" alarm_config_id="090013"></p:alarm>
    <p:alarm source="pt100_front_bearing_temperature" active_value="true" alarm_config_id="090014"></p:alarm>
    <p:alarm source="pt100_back_bearing_temperature" active_value="true" alarm_config_id="090015"></p:alarm>
    <p:alarm source="ptc_windings_temperature" active_value="true" alarm_config_id="090016"></p:alarm>
    <p:alarm source="engine_vibrations" active_value="true" alarm_config_id="090017"></p:alarm>
    <p:alarm source="warning_engine_vibrations" active_value="true" alarm_config_id="090018"></p:alarm>
    <p:alarm source="warning_engine_vibrations_signal_fail" active_value="true" alarm_config_id="090019"></p:alarm>
    <p:alarm source="ptc_trip_windings_temperature_state" active_value="true" alarm_config_id="090020"></p:alarm>
    <p:alarm source="relay_phases" active_value="true" alarm_config_id="090034"></p:alarm>
    <p:alarm source="actuator_1_opening_time_exceeded" active_value="true" alarm_config_id="090022"></p:alarm>
    <p:alarm source="actuator_1_closing_time_exceeded" active_value="true" alarm_config_id="090023"></p:alarm>
    <p:alarm source="actuator_1_electric_protection" active_value="true" alarm_config_id="090024"></p:alarm>
    <p:alarm source="actuator_2_opening_time_exceeded" active_value="true" alarm_config_id="090025"></p:alarm>
    <p:alarm source="actuator_2_closing_time_exceeded" active_value="true" alarm_config_id="090026"></p:alarm>
    <p:alarm source="actuator_2_electric_protection" active_value="true" alarm_config_id="090027"></p:alarm>
    <p:alarm source="axialfan_warning_plc_state" active_value="true" alarm_config_id="090030"></p:alarm>
    <p:alarm source="damper_present_trip" active_value="true" alarm_config_id="090031"></p:alarm>
    <p:alarm source="general_warning_present" active_value="true" alarm_config_id="090033"></p:alarm>
    <p:alarm source="warning_overvoltage" active_value="true" alarm_config_id="090036"></p:alarm>                        
    <p:alarm source="axial_direct_order" active_value="true" alarm_config_id="310009"></p:alarm>                            
    <p:alarm source="axial_reverse_order" active_value="true" alarm_config_id="310009"></p:alarm>                            
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/fullequip/adapters/mango/32_presurizacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="32">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>remote_control</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>pres_fan_1</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>pres_fan_2</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
  	<p:alarm source="alarm_emergency_button" active_value="true" alarm_config_id="060032"></p:alarm> 
    <p:alarm source="alarm_pres_fan_1" active_value="true" alarm_config_id="070032"></p:alarm>
    <p:alarm source="alarm_pres_fan_2" active_value="true" alarm_config_id="080032"></p:alarm>
     
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/fullequip/adapters/mango/86_pump.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="86">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>pump_on</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
		<p:alarm source="no_operation" active_value="true" alarm_config_id="020086"></p:alarm>
		<p:alarm source="no_auto_state" active_value="true" alarm_config_id="030086"></p:alarm>
		<p:alarm source="pump_on" active_value="true" alarm_config_id="040086"></p:alarm>
	</p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/dev/adapters/mango/55_ct_2alarms_2measures.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
    xmlns:p="json_generic_mango_v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " element_type_id="55">
    <p:session_uid element_type_param_id="1003" param_type_id="1" array_element_id="1,3,4,5"></p:session_uid>
    <p:state field="status">
        <p:state_value source="0" input="2" disconnected="true"></p:state_value>
        <p:state_value source="1" input="1"></p:state_value>
    </p:state>
    <p:fields>
        <p:field>
            <p:source>temperature</p:source>
            <p:input>
                <p:element_type_param_id>1</p:element_type_param_id>
                <p:param_type_id>2</p:param_type_id>
            </p:input>
        </p:field>
    </p:fields>
    <p:alarms>
        <p:alarm source="air_conditioner_state" active_value="true" alarm_config_id="176"></p:alarm>
        <p:alarm source="door_open" active_value="true" alarm_config_id="177"></p:alarm>
    </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/rits/resources/project/avo/adapters/mango/32_presurizacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="32">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
    <p:fields>
    <p:field>
      <p:source>local_remote</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>fan_running</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>reset_alarms</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	<p:field>
      <p:source>parcial_operating_hours</p:source>
      <p:input>
        <p:element_type_param_id>6</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    	<p:field>
      <p:source>total_operating_hours</p:source>
      <p:input>
        <p:element_type_param_id>7</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
    <p:alarm source="fan_fail" active_value="true" alarm_config_id="3204"></p:alarm>
    <p:alarm source="fan_fail_stop" active_value="true" alarm_config_id="3202"></p:alarm>
    <p:alarm source="fan_fail_start" active_value="true" alarm_config_id="3203"></p:alarm>   
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/avo/adapters/mango/22_valvulas_mariposa.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="22"
  array_element_id="3,4,9,10,15,16,21,22">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>state</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/ausol/adapters/mango/71_22_panel.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-istance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="71" array_element_id="5,6,10,11,14,39,80,81,82,83,84,85,86,87,88,89,90">
  <p:groovy_adapter file="InputAdapter_VMS_DGT_22.groovy"></p:groovy_adapter>
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>content</p:source>
	  <p:use_adapter>true</p:use_adapter>
    </p:field>
  <p:field>
      <p:source>travel_time_enabled</p:source>
      <p:input>
        <p:element_type_param_id>10</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>
