=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:p="json_generic_mango_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="json_generic_mango_v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="json_generic_mango_v1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="groovy_adapter" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:attribute name="file" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      	<xs:element name="session_uid">
          <xs:complexType>
            <xs:attribute name="element_type_param_id" type="xs:long" use="required" />
            <xs:attribute name="param_type_id" type="xs:long" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="state">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="state_value">
                <xs:complexType>
                  <xs:attribute name="source" type="xs:long" use="required" />
                  <xs:attribute name="input" type="xs:long" use="required" />
                  <xs:attribute name="disconnected" type="xs:boolean" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="field" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="fields" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="field">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="source" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="input" minOccurs="0" maxOccurs="1" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="element_type_param_id" type="xs:long" />
                          <xs:element name="param_type_id" type="xs:long" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="use_adapter" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="alarms" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="alarm">
                <xs:complexType>
                  <xs:attribute name="source" type="xs:string" use="required" />
                  <xs:attribute name="active_value" type="xs:string" use="required" />
                  <xs:attribute name="alarm_config_id" type="xs:long" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
      <xs:attribute name="element_type_id" type="xs:long" use="required" />
      <xs:attribute name="array_element_id" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/ausol/adapters/mango/15_linear_fire_detection.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
  xmlns:p="json_generic_mango_v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " 
  element_type_id="15">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>avg_temperature</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>max_temperature</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>min_temperature</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
    <p:alarm source="alarm_zone" active_value="true" alarm_config_id="256"></p:alarm>
    <p:alarm source="fiber_fault" active_value="true" alarm_config_id="257"></p:alarm>
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/avo/adapters/mango/11_sos_4alarms.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="11">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>vol_mic_reader</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>vol_audio_reader</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>test_audio_reader</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>last_day_test</p:source>
      <p:input>
        <p:element_type_param_id>6</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>last_month_test</p:source>
      <p:input>
        <p:element_type_param_id>7</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>last_year_test</p:source>
      <p:input>
        <p:element_type_param_id>8</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>last_hour_test</p:source>
      <p:input>
        <p:element_type_param_id>9</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>last_minute_test</p:source>
      <p:input>
        <p:element_type_param_id>10</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>last_second_test</p:source>
      <p:input>
        <p:element_type_param_id>11</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>foghorn_state</p:source>
      <p:input>
        <p:element_type_param_id>14</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
    <p:alarm source="sos_door_open" active_value="false" alarm_config_id="42"></p:alarm>
    <p:alarm source="extinguisher_door_open" active_value="false" alarm_config_id="306"></p:alarm>
    <p:alarm source="extinguisher_extraction" active_value="false" alarm_config_id="307"></p:alarm>
    <p:alarm source="sip" active_value="true" alarm_config_id="11001"></p:alarm>
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/maqueta_dgt_jaen/adapters/mango/71_18_panel.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="71" array_element_id="61,62">
  <p:groovy_adapter file="InputAdapter_VMS_DGT_18.groovy"></p:groovy_adapter>
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>content</p:source>
	    <p:use_adapter>true</p:use_adapter>
    </p:field>
    <p:field>
      <p:source>state</p:source>
	    <p:use_adapter>true</p:use_adapter>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/avo/adapters/mango/27_plc_CT02.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="27"
    array_element_id="2">
 <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>master_cpu_state</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	<p:field>
      <p:source>slave_cpu_state</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	<p:field>
      <p:source>master_cpu_function</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	<p:field>
      <p:source>slave_cpu_function</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>device_error_t1</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t2</p:source>
      <p:input>
        <p:element_type_param_id>6</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t3</p:source>
      <p:input>
        <p:element_type_param_id>7</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t4</p:source>
      <p:input>
        <p:element_type_param_id>8</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t5</p:source>
      <p:input>
        <p:element_type_param_id>9</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>device_error_t6</p:source>
      <p:input>
        <p:element_type_param_id>10</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t7</p:source>
      <p:input>
        <p:element_type_param_id>11</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t8</p:source>
      <p:input>
        <p:element_type_param_id>12</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t9</p:source>
      <p:input>
        <p:element_type_param_id>13</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t10</p:source>
      <p:input>
        <p:element_type_param_id>14</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t11</p:source>
      <p:input>
        <p:element_type_param_id>15</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t12</p:source>
      <p:input>
        <p:element_type_param_id>16</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t13</p:source>
      <p:input>
        <p:element_type_param_id>17</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t14</p:source>
      <p:input>
        <p:element_type_param_id>18</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t15</p:source>
      <p:input>
        <p:element_type_param_id>19</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t16</p:source>
      <p:input>
        <p:element_type_param_id>20</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t17</p:source>
      <p:input>
        <p:element_type_param_id>21</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t18</p:source>
      <p:input>
        <p:element_type_param_id>22</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t19</p:source>
      <p:input>
        <p:element_type_param_id>23</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t20</p:source>
      <p:input>
        <p:element_type_param_id>24</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
   	<p:field>
      <p:source>device_error_t21</p:source>
      <p:input>
        <p:element_type_param_id>25</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
   <p:alarms>
    <p:alarm source="upd_fail_1er1" active_value="true" alarm_config_id="30090027"></p:alarm>
    <p:alarm source="upd_fail_1er2" active_value="true" alarm_config_id="30100027"></p:alarm>
    <p:alarm source="upd_fail_1es0" active_value="true" alarm_config_id="30110027"></p:alarm>
    <p:alarm source="upd_fail_1e01" active_value="true" alarm_config_id="30120027"></p:alarm>
    <p:alarm source="upd_fail_1e02" active_value="true" alarm_config_id="30130027"></p:alarm>
    <p:alarm source="upd_fail_1e03" active_value="true" alarm_config_id="30140027"></p:alarm>
    <p:alarm source="upd_fail_1e04" active_value="true" alarm_config_id="30150027"></p:alarm>
    <p:alarm source="upd_fail_1e05" active_value="true" alarm_config_id="30160027"></p:alarm>
    <p:alarm source="upd_fail_ct02_1" active_value="true" alarm_config_id="30170027"></p:alarm>
    <p:alarm source="upd_fail_ct02_2" active_value="true" alarm_config_id="30180027"></p:alarm>
    <p:alarm source="process_error" active_value="true" alarm_config_id="040027"></p:alarm>
    <p:alarm source="master_comm" active_value="true" alarm_config_id="050027"></p:alarm>
    <p:alarm source="slave_comm" active_value="true" alarm_config_id="060027"></p:alarm>
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/openits_plus_2/adapters/mango/65_sai.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
  xmlns:p="json_generic_mango_v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " element_type_id="65">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>bypass</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	  <p:field>
      <p:source>power_fail</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	  <p:field>
      <p:source>temperature</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	  <p:field>
      <p:source>L1</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	  <p:field>
      <p:source>L2</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	  <p:field>
      <p:source>L3</p:source>
      <p:input>
        <p:element_type_param_id>6</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
	  <p:field>
      <p:source>autonomy</p:source>
      <p:input>
        <p:element_type_param_id>7</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
    <p:alarm source="alarm_battery_bad" active_value="true" alarm_config_id="020065"></p:alarm>
    <p:alarm source="alarm_on_battery" active_value="true" alarm_config_id="030065"></p:alarm>
    <p:alarm source="alarm_low_battery" active_value="true" alarm_config_id="040065"></p:alarm>
    <p:alarm source="alarm_depleted_battery" active_value="true" alarm_config_id="050065"></p:alarm>
    <p:alarm source="alarm_temperature_bad" active_value="true" alarm_config_id="060065"></p:alarm>
    <p:alarm source="alarm_input_bad" active_value="true" alarm_config_id="070065"></p:alarm>
    <p:alarm source="alarm_output_overload" active_value="true" alarm_config_id="080065"></p:alarm>
    <p:alarm source="alarm_ups_off_as_requested" active_value="true" alarm_config_id="090065"></p:alarm>
    <p:alarm source="alarm_charger_failed" active_value="true" alarm_config_id="100065"></p:alarm>
    <p:alarm source="alarm_ups_output_off" active_value="true" alarm_config_id="110065"></p:alarm>
    <p:alarm source="alarm_fan_failure" active_value="true" alarm_config_id="120065"></p:alarm>
    <p:alarm source="alarm_fuse_failure" active_value="true" alarm_config_id="130065"></p:alarm>
    <p:alarm source="alarm_diagnostic_test_failed" active_value="true" alarm_config_id="140065"></p:alarm>
    <p:alarm source="alarm_communications_lost" active_value="true" alarm_config_id="150065"></p:alarm>
    <p:alarm source="alarm_awaiting_power" active_value="true" alarm_config_id="160065"></p:alarm>
    <p:alarm source="alarm_shutdown_pending" active_value="true" alarm_config_id="170065"></p:alarm>
    <p:alarm source="alarm_shutdown_imminent" active_value="true" alarm_config_id="180065"></p:alarm>
    <p:alarm source="alarm_test_in_progress" active_value="true" alarm_config_id="190065"></p:alarm>
    <p:alarm source="alarm_general_fail" active_value="true" alarm_config_id="200065"></p:alarm>
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/mango/02_camera.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="2">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
    <p:fields>
    <p:field>
      <p:source>image</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
     <p:field>
      <p:source>video</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>id_incident</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>place</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
        <p:field>
      <p:source>type_incident</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>
