=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:p="json_generic_mango_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="json_generic_mango_v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="json_generic_mango_v1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="groovy_adapter" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:attribute name="file" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      	<xs:element name="session_uid">
          <xs:complexType>
            <xs:attribute name="element_type_param_id" type="xs:long" use="required" />
            <xs:attribute name="param_type_id" type="xs:long" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="state">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="state_value">
                <xs:complexType>
                  <xs:attribute name="source" type="xs:long" use="required" />
                  <xs:attribute name="input" type="xs:long" use="required" />
                  <xs:attribute name="disconnected" type="xs:boolean" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="field" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="fields" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="field">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="source" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="input" minOccurs="0" maxOccurs="1" >
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="element_type_param_id" type="xs:long" />
                          <xs:element name="param_type_id" type="xs:long" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="use_adapter" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="alarms" minOccurs="0" maxOccurs="1" >
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="alarm">
                <xs:complexType>
                  <xs:attribute name="source" type="xs:string" use="required" />
                  <xs:attribute name="active_value" type="xs:string" use="required" />
                  <xs:attribute name="alarm_config_id" type="xs:long" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
      <xs:attribute name="element_type_id" type="xs:long" use="required" />
      <xs:attribute name="array_element_id" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/bratislava/adapters/mango/71_4_panel_1_alarm.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="71"
	array_element_id="80">
  <p:groovy_adapter file="InputAdapter_VMS_NTCIP_4.groovy"></p:groovy_adapter>
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>brightness</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>temperature</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>content</p:source>
	  <p:use_adapter>true</p:use_adapter>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/dev/adapters/mango/74_eru_slave.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
	xmlns:p="json_generic_mango_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " 
	element_type_id="74" array_element_id="2">
	<p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
	<p:state field="status">
		<p:state_value source="0" input="2" disconnected="true"></p:state_value>
		<p:state_value source="1" input="1"></p:state_value>
	</p:state>
	<p:fields>
		<p:field>
			<p:source>peripheral_ctrl</p:source>
			<p:input>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:input>
		</p:field>
	</p:fields>
	<p:alarms>
		<p:alarm source="redun_comm" active_value="false" alarm_config_id="220"></p:alarm>
		<p:alarm source="peripheral_ctrl" active_value="true" alarm_config_id="221"></p:alarm>
	</p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/rits/resources/project/ruta_mina/adapters/mango/25_electrical_cabinet_2alarms.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="25" array_element_id="38,39,40,41,42,43,44">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:alarms>
    <p:alarm source="door_open" active_value="false" alarm_config_id="030025"></p:alarm>
    <p:alarm source="overvoltage" active_value="true" alarm_config_id="080025"></p:alarm>
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/mango/48_toxic_control.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="48">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>opening_gate</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>gate_opened</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
  	<p:alarm source="selector_auto_manual" active_value="false" alarm_config_id="020048"></p:alarm> 
    <p:alarm source="gate_going_down" active_value="true" alarm_config_id="030048"></p:alarm>
    <p:alarm source="gate_malfunction" active_value="true" alarm_config_id="040048"></p:alarm>
    <p:alarm source="gate_lowered" active_value="true" alarm_config_id="050048"></p:alarm>    
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/dgt_jaen/adapters/mango/11_sos.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
  xmlns:p="json_generic_mango_v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " 
    element_type_id="11">
  <p:groovy_adapter file="InputAdapter_SOS.groovy"></p:groovy_adapter>
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>  
  <p:fields>
    <p:field>
      <p:source>res_meg_qry</p:source>
	  <p:use_adapter>true</p:use_adapter>
    </p:field>
    <p:field>
      <p:source>res_tst_man</p:source>
	  <p:use_adapter>true</p:use_adapter>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/bratislava/adapters/mango/71_23_panel.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1
 name=""
  version=""
  xmlns:p="json_generic_mango_v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd " 
  element_type_id="71" 	
  array_element_id="167,168,169,170,171,172,173,174,175,176">
  <p:groovy_adapter file="InputAdapter_VMS_ROTAPANEL.groovy"></p:groovy_adapter>
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>switch_on_read</p:source>
      <p:use_adapter>true</p:use_adapter>
    </p:field>
  </p:fields>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/mango/75_power_station.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 
	name="" 
	version="" 
	xmlns:p="json_generic_mango_v1" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="75">
  <p:session_uid element_type_param_id="1003" param_type_id="1"></p:session_uid>
  <p:state field="status">
    <p:state_value source="0" input="2" disconnected="true"></p:state_value>
    <p:state_value source="1" input="1"></p:state_value>
  </p:state>
  <p:fields>
    <p:field>
      <p:source>grp_corriente_fase_1</p:source>
      <p:input>
        <p:element_type_param_id>1</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_corriente_fase_2</p:source>
      <p:input>
        <p:element_type_param_id>2</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_corriente_fase_3</p:source>
      <p:input>
        <p:element_type_param_id>3</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_frecuencia_salida</p:source>
      <p:input>
        <p:element_type_param_id>4</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_horas_tot_marcha</p:source>
      <p:input>
        <p:element_type_param_id>5</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_rpm_generador</p:source>
      <p:input>
        <p:element_type_param_id>6</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_tension_bateria</p:source>
      <p:input>
        <p:element_type_param_id>7</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_tension_salida_gen</p:source>
      <p:input>
        <p:element_type_param_id>8</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_modo_operacion_off</p:source>
      <p:input>
        <p:element_type_param_id>9</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_modo_operacion_man</p:source>
      <p:input>
        <p:element_type_param_id>10</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_modo_operacion_aut</p:source>
      <p:input>
        <p:element_type_param_id>11</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_vol_gen_L1_N</p:source>
      <p:input>
        <p:element_type_param_id>12</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_vol_gen_L2_N</p:source>
      <p:input>
        <p:element_type_param_id>13</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_vol_gen_L3_N</p:source>
      <p:input>
        <p:element_type_param_id>14</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_gas_level</p:source>
      <p:input>
        <p:element_type_param_id>15</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_temp_rad</p:source>
      <p:input>
        <p:element_type_param_id>16</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
    <p:field>
      <p:source>grp_kwh</p:source>
      <p:input>
        <p:element_type_param_id>17</p:element_type_param_id>
        <p:param_type_id>2</p:param_type_id>
      </p:input>
    </p:field>
  </p:fields>
  <p:alarms>
    <p:alarm source="grp_alarma_temperatura" active_value="true" alarm_config_id="223"></p:alarm>
    <p:alarm source="grp_alarma_general" active_value="true" alarm_config_id="224"></p:alarm>
    <p:alarm source="grp_motor_encendido" active_value="true" alarm_config_id="225"></p:alarm>
    <p:alarm source="grp_nivel_combust_rsv" active_value="true" alarm_config_id="226"></p:alarm>
  </p:alarms>
</p:json_generic_mango_v1>

=== SCADA-ITS/configscada/resources/project/dev/adapters/mango/28_vms_Mat_192_64.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:json_generic_mango_v1 name="" version=""
	xmlns:p="json_generic_mango_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="json_generic_mango_v1 ../../../adapter-lib/src/main/resources/schemas/mango/json_generic_mango_v1.xsd "
	element_type_id="28">
	<p:groovy_adapter file="VmsMat192ParamsAdapter.groovy"></p:groovy_adapter>
	<p:session_uid element_type_param_id="1003"
		param_type_id="1"></p:session_uid>
	<p:state field="status">
		<p:state_value source="0" input="2" disconnected="true"></p:state_value>
		<p:state_value source="1" input="1"></p:state_value>
	</p:state>
	<p:fields>
		<p:field>
			<p:source>brightness</p:source>
			<p:input>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:input>
		</p:field>
		<p:field>
			<p:source>brightness_ctrl</p:source>
			<p:input>
				<p:element_type_param_id>2</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:input>
		</p:field>
		<p:field>
			<p:source>temperature</p:source>
			<p:input>
				<p:element_type_param_id>3</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:input>
		</p:field>
		<p:field>
			<p:source>current_message_multistring</p:source>
			<p:use_adapter>true</p:use_adapter>
		</p:field>
	</p:fields>
	<p:alarms>
		<p:alarm source="pixel_error" active_value="1"
			alarm_config_id="88"></p:alarm>
		<p:alarm source="photocell_error" active_value="1"
			alarm_config_id="89"></p:alarm>
		<p:alarm source="temp_warning_error" active_value="1"
			alarm_config_id="90"></p:alarm>
		<p:alarm source="temp_critical_error" active_value="1"
			alarm_config_id="91"></p:alarm>
		<p:alarm source="door_open_error" active_value="1"
			alarm_config_id="92"></p:alarm>
	</p:alarms>
</p:json_generic_mango_v1>
