=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	attributeFormDefault="unqualified"
	targetNamespace="historical_element_parser_v1"
	elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element
		name="historical_element_parser_v1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="target_table" type="xs:string" />
				<xs:element name="table_space" type="xs:string" />
				<xs:element name="field_element_id" type="xs:string" />
				<xs:element name="field_timestamp" type="xs:string" minOccurs="0" maxOccurs ="1"/>
				<xs:element name="cron_expression" type="xs:string" minOccurs="0" maxOccurs ="1"/>
				<xs:element name="no_save_empty_rows" type="xs:boolean" minOccurs="0" maxOccurs ="1"/>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="field">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="element_type_param">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="element_type_param_id"
														type="xs:unsignedByte" />
													<xs:element name="param_type_id"
														type="xs:unsignedByte" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"
										use="required" />
									<xs:attribute name="pk" type="xs:boolean"
										use="optional" />
									<xs:attribute name="indexed" type="xs:boolean"
										use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="element_type_id"
				type="xs:unsignedByte" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/avo/adapters/manager/historical-manager/element_type/01.ws.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_element_parser_v1
	xmlns:p="historical_element_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_element_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd"
	element_type_id="1">
	<p:target_table>hist.ws</p:target_table>
	<p:table_space>tbl_hist</p:table_space>
	<p:field_element_id>f_element_id</p:field_element_id>
	<p:field_timestamp>timestamp_at</p:field_timestamp>
	<p:cron_expression>0 * * ? * * *</p:cron_expression>
	<p:fields>
		<p:field name="Surface_Temperature">
			<p:element_type_param>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Freeze_Point">
			<p:element_type_param>
				<p:element_type_param_id>3</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Air_Pressure">
			<p:element_type_param>
				<p:element_type_param_id>4</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Water_Depth">
			<p:element_type_param>
				<p:element_type_param_id>5</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Road_Condition">
			<p:element_type_param>
				<p:element_type_param_id>9</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Relative_Humidity">
			<p:element_type_param>
				<p:element_type_param_id>10</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Precipitation_Intensity">
			<p:element_type_param>
				<p:element_type_param_id>11</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Average_Wind_Speed">
			<p:element_type_param>
				<p:element_type_param_id>13</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Average_Wind_Direction">
			<p:element_type_param>
				<p:element_type_param_id>14</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Air_Temperature">
			<p:element_type_param>
				<p:element_type_param_id>17</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Precipitation_Type">
			<p:element_type_param>
				<p:element_type_param_id>19</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Visibility">
			<p:element_type_param>
				<p:element_type_param_id>20</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Precipitation_Quantity">
			<p:element_type_param>
				<p:element_type_param_id>23</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Ice_Percent">
			<p:element_type_param>
				<p:element_type_param_id>24</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="Friction">
			<p:element_type_param>
				<p:element_type_param_id>25</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
	</p:fields>
</p:historical_element_parser_v1>

=== SCADA-ITS/configscada/rits/resources/project/avo/adapters/manager/historical-manager/element_type/86.pump.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_element_parser_v1
	xmlns:p="historical_element_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_element_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd"
	element_type_id="86">
	<p:target_table>hist.pump</p:target_table>
	<p:table_space>tbl_hist</p:table_space>
	<p:field_element_id>f_element_id</p:field_element_id>
	<p:field_timestamp>timestamp_at</p:field_timestamp>
	<p:cron_expression>0 * * ? * * *</p:cron_expression>
	<p:fields>
		<p:field name="pump_on">
			<p:element_type_param>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
	</p:fields>
</p:historical_element_parser_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/manager/historical-manager/element_type/09.fan.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_element_parser_v1
	xmlns:p="historical_element_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_element_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd"
	element_type_id="9">
	<p:target_table>hist.fan</p:target_table>
	<p:table_space>tbl_hist</p:table_space>
	<p:field_element_id>f_element_id</p:field_element_id>
	<p:field_timestamp>timestamp_at</p:field_timestamp>
	<p:cron_expression>0 * * ? * * *</p:cron_expression>
 	<p:fields>
		<p:field name="fan_state">
			<p:element_type_param>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="parcial_operating_hours">
			<p:element_type_param>
				<p:element_type_param_id>14</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="total_operating_hours">
			<p:element_type_param>
				<p:element_type_param_id>15</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="n_starts">
			<p:element_type_param>
				<p:element_type_param_id>27</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
	</p:fields>
</p:historical_element_parser_v1>

=== SCADA-ITS/configscada/resources/project/openits_plus_2/adapters/manager/historical-manager/element_type/09.jetfan.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_element_parser_v1
	xmlns:p="historical_element_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_element_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd"
	element_type_id="9">
	<p:target_table>hist.fan</p:target_table>
	<p:table_space>tbl_hist</p:table_space>
	<p:field_element_id>f_element_id</p:field_element_id>
	<p:field_timestamp>timestamp_at</p:field_timestamp>
 	<p:fields>
		<p:field name="fan_state">
			<p:element_type_param>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="fan_vibration">
			<p:element_type_param>
				<p:element_type_param_id>2</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="front_bearing_temperature">
			<p:element_type_param>
				<p:element_type_param_id>3</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="back_bearing_temperature">
			<p:element_type_param>
				<p:element_type_param_id>4</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
	</p:fields>
</p:historical_element_parser_v1>

=== SCADA-ITS/configscada/resources/project/ausol/adapters/manager/historical-manager/element_type/03.detector.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_element_parser_v1
	xmlns:p="historical_element_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_element_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd"
	element_type_id="3">
	<p:target_table>hist.det_revenga</p:target_table>
	<p:table_space>tbl_hist</p:table_space>
	<p:field_element_id>f_element_id</p:field_element_id>
	<p:fields>
		<p:field name="date" pk="true" indexed="true">
			<p:element_type_param>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="n_vehicles">
			<p:element_type_param>
				<p:element_type_param_id>4</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="occupancy">
			<p:element_type_param>
				<p:element_type_param_id>6</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="congestion">
			<p:element_type_param>
				<p:element_type_param_id>7</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="speed">
			<p:element_type_param>
				<p:element_type_param_id>9</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="gap">
			<p:element_type_param>
				<p:element_type_param_id>10</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="length">
			<p:element_type_param>
				<p:element_type_param_id>17</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="veh_length_1">
			<p:element_type_param>
				<p:element_type_param_id>20</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="veh_length_2">
			<p:element_type_param>
				<p:element_type_param_id>21</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="veh_speed_1">
			<p:element_type_param>
				<p:element_type_param_id>40</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="veh_speed_2">
			<p:element_type_param>
				<p:element_type_param_id>41</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
		<p:field name="veh_speed_3">
			<p:element_type_param>
				<p:element_type_param_id>42</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
	</p:fields>
</p:historical_element_parser_v1>

=== SCADA-ITS/configscada/resources/project/dgt_jaen/adapters/manager/historical-manager/element_type/08.barrier.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_element_parser_v1
	xmlns:p="historical_element_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_element_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_element_parser_v1.xsd"
	element_type_id="8">
	<p:target_table>hist.barrier</p:target_table>
	<p:table_space>tbl_hist</p:table_space>
	<p:field_element_id>f_element_id</p:field_element_id>
	<p:field_timestamp>timestamp_at</p:field_timestamp>
	<p:fields>
		<p:field name="bar_state">
			<p:element_type_param>
				<p:element_type_param_id>1</p:element_type_param_id>
				<p:param_type_id>2</p:param_type_id>
			</p:element_type_param>
		</p:field>
	</p:fields>
</p:historical_element_parser_v1>
