=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/manager/historical_audit_log_parser_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	attributeFormDefault="unqualified"
	targetNamespace="historical_audit_log_parser_v1"
	elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element
		name="historical_audit_log_parser_v1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="target_table" type="xs:string" />
				<xs:element name="table_space" type="xs:string" />
				<xs:element name="field_log_subtype_id" type="xs:string"  minOccurs="0" maxOccurs ="1"/>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="field">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="log_type_param_id"
											type="xs:unsignedByte" />
									</xs:sequence>
									<xs:attribute name="name" type="xs:string"
										use="required" />
									<xs:attribute name="indexed" type="xs:boolean"
										use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="log_type_id" type="xs:unsignedByte"
				use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/navarra_pro/adapters/manager/historical-manager/log_type/processes.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_audit_log_parser_v1
	xmlns:p="historical_audit_log_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_audit_log_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_audit_log_parser_v1.xsd"
	log_type_id="5">
	<p:target_table>hist.audit_processes</p:target_table>
	<p:table_space>tbs_controltrafico_hist</p:table_space>
	<p:field_log_subtype_id>log_subtype_id</p:field_log_subtype_id>
	<p:fields>
		<p:field name="process" indexed="true">
				<p:log_type_param_id>1</p:log_type_param_id>
		</p:field>
		<p:field name="running_since" indexed="true">
				<p:log_type_param_id>2</p:log_type_param_id>
		</p:field>
		<p:field name="comment">
				<p:log_type_param_id>3</p:log_type_param_id>
		</p:field>
	</p:fields>
</p:historical_audit_log_parser_v1>

=== SCADA-ITS/configscada/resources/project/navarra_pre/adapters/manager/historical-manager/log_type/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_audit_log_parser_v1
	xmlns:p="historical_audit_log_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_audit_log_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_audit_log_parser_v1.xsd"
	log_type_id="3">
	<p:target_table>hist.audit_commands</p:target_table>
	<p:table_space>tbs_controltrafico_hist</p:table_space>
	<p:field_log_subtype_id>log_subtype_id</p:field_log_subtype_id>
	<p:fields>
		<p:field name="command_type" indexed="true">
				<p:log_type_param_id>1</p:log_type_param_id>
		</p:field>
		<p:field name="element" indexed="true">
				<p:log_type_param_id>2</p:log_type_param_id>
		</p:field>
		<p:field name="command_values">
				<p:log_type_param_id>3</p:log_type_param_id>
		</p:field>
		<p:field name="comment">
				<p:log_type_param_id>4</p:log_type_param_id>
		</p:field>
	</p:fields>
</p:historical_audit_log_parser_v1>

=== SCADA-ITS/configscada/resources/project/navarra_pro/adapters/manager/historical-manager/log_type/plans.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:historical_audit_log_parser_v1
	xmlns:p="historical_audit_log_parser_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="historical_audit_log_parser_v1 ../../../../../adapter-lib/src/main/resources/schemas/manager/historical_audit_log_parser_v1.xsd"
	log_type_id="2">
	<p:target_table>hist.audit_plans</p:target_table>
	<p:table_space>tbs_controltrafico_hist</p:table_space>
	<p:field_log_subtype_id>log_subtype_id</p:field_log_subtype_id>
	<p:fields>
		<p:field name="plan" indexed="true">
			<p:log_type_param_id>1</p:log_type_param_id>
		</p:field>
		<p:field name="arg">
			<p:log_type_param_id>2</p:log_type_param_id>
		</p:field>
		<p:field name="comment">
			<p:log_type_param_id>3</p:log_type_param_id>
		</p:field>
	</p:fields>
</p:historical_audit_log_parser_v1>
