=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:p="manager_adapter_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="manager_adapter_v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="manager_adapter_v1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="subscriptors" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="subscriptor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:unsignedByte" />
                    <xs:element name="enabled" type="xs:boolean" />
                    <xs:element name="entity" type="xs:string" />
                    <xs:element name="entity_pks" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="entity_pk" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="cmd_timestamp_filter" type="xs:unsignedByte" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="executors">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="executor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:unsignedByte" />
                    <xs:element name="enabled" type="xs:boolean" />
                    <xs:element name="threads" type="xs:unsignedByte" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="thread_redirect_criteria" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="time_to_start_s" type="xs:long" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="merge_wait_time" type="xs:long" />
                    <xs:element name="manager_class" type="xs:string" />
                    <xs:element name="custom_ready_executor" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="manager_params" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="manager_param_value" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="subscriptors_ref" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="subscriptor_id_ref" type="xs:unsignedByte" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="executor_params" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="executor_param_value" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/dev/adapters/manager/virtual_equipment_manager_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:manager_adapter_v1 name="" version=""
	xmlns:p="manager_adapter_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="manager_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd ">
	<p:subscriptors>
		<p:subscriptor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SendFramesCommand</p:entity>
		</p:subscriptor>

	</p:subscriptors>
	<p:executors>
		<p:executor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.virtual.equipment.manager.une.UneExecutor</p:manager_class>
			<p:subscriptors_ref>
				<p:subscriptor_id_ref>1</p:subscriptor_id_ref>
			</p:subscriptors_ref>
			<p:executor_params>
				<p:executor_param_value>cron_job=last_period_data_task_job;com.revenga.rits.back.virtual.equipment.manager.une.sheduler.RequestFrameJob;0 * * * * ?;0x07</p:executor_param_value>
				<p:executor_param_value>cron_job=get_traffic_infraction;com.revenga.rits.back.virtual.equipment.manager.une.sheduler.GetTrafficInfractionsJob;0 * * * * ?;3;/home/agomez/radar</p:executor_param_value>
				<p:executor_param_value>elementType=99</p:executor_param_value>
			</p:executor_params>
		</p:executor>

	</p:executors>
</p:manager_adapter_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/manager/io_external_manager_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:manager_adapter_v1 name="" version=""
	xmlns:p="manager_adapter_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="manager_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd ">
	<p:subscriptors>
		<p:subscriptor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetAlarmsPublishCommand</p:entity>
		</p:subscriptor>
	</p:subscriptors>
	<p:executors>
		<p:executor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:threads>4</p:threads>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.io.external.manager.executor.SendMailAlarmExecutor</p:manager_class>
			<p:subscriptors_ref>
				<p:subscriptor_id_ref>1</p:subscriptor_id_ref>
			</p:subscriptors_ref>
			<p:executor_params>
				<p:executor_param_value>road_file_path=adapters/manager/io-external-manager/roads.properties</p:executor_param_value>
				<p:executor_param_value>translation_file_path=adapters/manager/io-external-manager/i18n.properties</p:executor_param_value>
				<p:executor_param_value>element_file_path=adapters/manager/io-external-manager/elementTypes.properties</p:executor_param_value>
				<p:executor_param_value>recipients_file_path=adapters/manager/io-external-manager/recipients.properties</p:executor_param_value>
				<p:executor_param_value>body_file_path=adapters/manager/io-external-manager/bodyHTML.properties</p:executor_param_value>
				<p:executor_param_value>alarm_levels=2,3,4,5,6</p:executor_param_value>
				<p:executor_param_value>date_format=dd/MM/yyyy - HH:mm:ss</p:executor_param_value>
				<p:executor_param_value>subject=Alarma nivel %level%: %element%</p:executor_param_value>
  			</p:executor_params>
		</p:executor>
	</p:executors>
</p:manager_adapter_v1>

=== SCADA-ITS/configscada/rits/resources/project/maqueta_ruta_mina/adapters/manager/io_external_manager_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:manager_adapter_v1 name="" version=""
	xmlns:p="manager_adapter_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="manager_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd ">
	<p:subscriptors>
		<p:subscriptor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetAlarmsPublishCommand</p:entity>
		</p:subscriptor>
	</p:subscriptors>
	<p:executors>
		<p:executor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:threads>4</p:threads>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.io.external.manager.tcman.TCMANExecutor</p:manager_class>
			<p:subscriptors_ref>
				<p:subscriptor_id_ref>1</p:subscriptor_id_ref>
			</p:subscriptors_ref>
			<p:executor_params>
				<p:executor_param_value>alarm_types=4</p:executor_param_value>
				<p:executor_param_value>date_format=yyyy-MM-dd'T'HH:mm:ss.SSS'Z'</p:executor_param_value>
				<p:executor_param_value>url=http://10.133.50.32/GIMWebApi/api/REVENGA/Aviso/</p:executor_param_value>
				<p:executor_param_value>time_zone=America/Santiago</p:executor_param_value>
				<p:executor_param_value>KEY=BCA0FCE2-55E1-426D-8B00-D33C5AC97AB6</p:executor_param_value>
				<p:executor_param_value>client_alias=OpenITS</p:executor_param_value>
				<p:executor_param_value>user_name=admin</p:executor_param_value>
				<p:executor_param_value>GIM_id=0</p:executor_param_value>
				<p:executor_param_value>GIM_number=0</p:executor_param_value>
	  		</p:executor_params>
		</p:executor>
	</p:executors>
</p:manager_adapter_v1>

=== SCADA-ITS/configscada/resources/project/navarra_lab/adapters/manager/transit_manager_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:manager_adapter_v1 name="" version=""
	xmlns:p="manager_adapter_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="manager_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd ">
	<p:subscriptors>
		<p:subscriptor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetChangeStateTransitCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>2</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetChangeAssignedUserTransitCommand</p:entity>
		</p:subscriptor>
	</p:subscriptors>
	<p:executors>
  <p:executor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.transit.manager.transit.recovery.une199121.TransitRecoveryUne199121Executor</p:manager_class>
			<p:executor_params>
				<p:executor_param_value>cron_job=TransitRecoveryJob;recoveryUne199121_4Transits;0 * * * * ?;300;secring_Revenga.gpg;BjXId2LO9Wx+4eMIMJQEMNOl9TDp/bhl9RtFe9BkK2M=</p:executor_param_value>
				<p:executor_param_value>elementType=99</p:executor_param_value>
				<p:executor_param_value>elementSubtype=1</p:executor_param_value>
			</p:executor_params>
		</p:executor>
		<p:executor>
			<p:id>2</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.transit.manager.transit.persistence.TransitPersistenceExecutor</p:manager_class>
			<p:subscriptors_ref>
				<p:subscriptor_id_ref>1</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>2</p:subscriptor_id_ref>
			</p:subscriptors_ref>
		</p:executor>		
		<p:executor>
			<p:id>3</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.transit.manager.cgi.api.multas.CgiApiMultasExecutor</p:manager_class>
			<p:executor_params>
				<p:executor_param_value><![CDATA[cron_expression=0 * * * * ?]]></p:executor_param_value>
			</p:executor_params>	
		</p:executor>
		<p:executor>
			<p:id>4</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.transit.manager.transit.persistence.TransitArchiverExecutor</p:manager_class>
			<p:executor_params>
				<p:executor_param_value><![CDATA[cron_expression_archiver=0 * * * * ?]]></p:executor_param_value>
				<p:executor_param_value><![CDATA[default_archive_after_minutes=1]]></p:executor_param_value>
				<p:executor_param_value><![CDATA[max_transits_to_archive=50]]></p:executor_param_value>
			</p:executor_params>	
		</p:executor>
	</p:executors>
</p:manager_adapter_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/manager/virtual_equipment_manager_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:manager_adapter_v1 name="" version=""
	xmlns:p="manager_adapter_v1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="manager_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd ">
	<p:subscriptors>
		<p:subscriptor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetFansStartCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>2</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetFansStopCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>3</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetFansStartReverseCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>4</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetVentilationModeCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>5</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetVentilationRegimeCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>6</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetAlarmsToVentilationCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>7</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetElementStatesToVentilationCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>8</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetElementValuesToVentilationCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>9</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetFireAlarmCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>10</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetIlluminationModeCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>11</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetIlluminationRegimeCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>12</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetAlarmsToIlluminationCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>13</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetElementStatesToIlluminationCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>14</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetElementValuesToIlluminationCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>15</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetCircuitsOffCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>16</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetCircuitsOnCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>17</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetDaliIlluminationRegimeCommand</p:entity>
		</p:subscriptor>
		<p:subscriptor>
			<p:id>18</p:id>
			<p:enabled>true</p:enabled>
			<p:entity>SetFansResetTotalHoursCommand</p:entity>
		</p:subscriptor>
	</p:subscriptors>
	<p:executors>
		<p:executor>
			<p:id>1</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.virtual.equipment.manager.tunnel.ventilation.TunnelVentilationSystemExecutor</p:manager_class>
			<p:subscriptors_ref>
				<p:subscriptor_id_ref>1</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>2</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>3</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>4</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>5</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>6</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>7</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>8</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>9</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>18</p:subscriptor_id_ref>
			</p:subscriptors_ref>
		</p:executor>
		<p:executor>
			<p:id>2</p:id>
			<p:enabled>true</p:enabled>
			<p:merge_wait_time>1</p:merge_wait_time>
			<p:manager_class>com.revenga.rits.back.virtual.equipment.manager.tunnel.illumination.TunnelIlluminationSystemExecutor</p:manager_class>
			<p:subscriptors_ref>
				<p:subscriptor_id_ref>10</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>11</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>12</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>13</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>14</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>15</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>16</p:subscriptor_id_ref>
				<p:subscriptor_id_ref>17</p:subscriptor_id_ref>
			</p:subscriptors_ref>
		</p:executor>
	</p:executors>
</p:manager_adapter_v1>

=== SCADA-ITS/configscada/rits/resources/master/adapters/manager/equipment_manager_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:manager_adapter_v1 name="" version="" xmlns:p="manager_adapter_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="manager_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/manager/manager_adapter_v1.xsd ">
  <p:subscriptors>
    <p:subscriptor>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetElementStatesChangeCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>2</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetElementMeasuresChangeCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>3</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetAlarmsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>4</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetActivationAlarmsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>5</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetDeactivationAlarmsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>6</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetRecognizeAlarmsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>7</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetAlarmsFilteredCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>8</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetSignallingsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>9</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetAddCommandsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>10</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetDeleteCommandsCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>11</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SetPriorityComand</p:entity>
    </p:subscriptor>
  </p:subscriptors>
  <p:executors>
    <p:executor>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>2</p:threads>
      <p:merge_wait_time>0</p:merge_wait_time>
      <p:manager_class>com.revenga.rits.back.equipment.manager.executor.ElementStateExecutor</p:manager_class>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>1</p:subscriptor_id_ref>
      </p:subscriptors_ref>
      <p:executor_params>
		<p:executor_param_value>expire_time_s=3</p:executor_param_value>
	  </p:executor_params>
    </p:executor>
    <p:executor>
      <p:id>2</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>2</p:threads>
      <p:merge_wait_time>0</p:merge_wait_time>
      <p:manager_class>com.revenga.rits.back.equipment.manager.executor.ElementValueExecutor</p:manager_class>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>2</p:subscriptor_id_ref>
      </p:subscriptors_ref>
      <p:executor_params>
		<p:executor_param_value>expire_time_s=3</p:executor_param_value>
	  </p:executor_params>
    </p:executor>
    <p:executor>
      <p:id>3</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>2</p:threads>
      <p:merge_wait_time>0</p:merge_wait_time>
      <p:manager_class>com.revenga.rits.back.equipment.manager.executor.ElementCommandExecutor</p:manager_class>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>4</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>5</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>6</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>7</p:subscriptor_id_ref>
      </p:subscriptors_ref>
      <p:executor_params>
		<p:executor_param_value>expire_time_s=3</p:executor_param_value>
	  </p:executor_params>
    </p:executor>
    <p:executor>
      <p:id>4</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>1</p:threads>
      <p:merge_wait_time>0</p:merge_wait_time>
      <p:manager_class>com.revenga.rits.back.equipment.manager.executor.DBSyncMeasuresExecutor</p:manager_class>
      <p:executor_params>
		<p:executor_param_value><![CDATA[cron_save_element_values= 0 * * * * ?]]></p:executor_param_value>
	  </p:executor_params>
    </p:executor>
    <p:executor>
      <p:id>5</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>1</p:threads>
      <p:merge_wait_time>0</p:merge_wait_time>
      <p:manager_class>com.revenga.rits.back.equipment.manager.executor.SignallingCommandsExecutor</p:manager_class>
      <p:executor_params>
		<p:executor_param_value><![CDATA[cron_maintenance_pm_queue= 5 * * * * ?]]></p:executor_param_value>
	  </p:executor_params>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>8</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>9</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>10</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>11</p:subscriptor_id_ref>
      </p:subscriptors_ref>
    </p:executor>
  </p:executors>
</p:manager_adapter_v1>
