=== SCADA-ITS/configscada/ritsback/adapter-lib/src/main/resources/schemas/controller/controller_adapter_v1.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:p="controller_adapter_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="controller_adapter_v1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="controller_adapter_v1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="subscriptors">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="subscriptor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:unsignedByte" />
                    <xs:element name="enabled" type="xs:boolean" />
                    <xs:element name="entity" type="xs:string" />
                    <xs:element name="entity_pks" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="entity_pk" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mods">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="mod">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="type" type="xs:long"/>
                    <xs:element name="id" type="xs:long"/>
                    <xs:element name="enabled" type="xs:boolean"/>
                    <xs:element name="threads" type="xs:unsignedByte" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="subscriptors_ref" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="subscriptor_id_ref" type="xs:unsignedByte" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="mod_params" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="mod_param_value" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="version" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SCADA-ITS/configscada/resources/project/avo/controller/controller_adapter_v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:controller_adapter_v1 name="" version="" xmlns:p="controller_adapter_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="controller_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/controller/controller_adapter_v1.xsd ">
  <p:subscriptors>
    <p:subscriptor>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>SignallingCommand</p:entity>
    </p:subscriptor>
    <p:subscriptor>
      <p:id>2</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>RequestCommand</p:entity>
    </p:subscriptor>
  </p:subscriptors>
  <p:mods>
    <p:mod>
      <p:type>1</p:type>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>10</p:threads>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>1</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>2</p:subscriptor_id_ref>
      </p:subscriptors_ref>
    </p:mod>
    <p:mod>
      <p:type>1</p:type>
      <p:id>2</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>2</p:threads>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>1</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>2</p:subscriptor_id_ref>
      </p:subscriptors_ref>
    </p:mod>
    <p:mod>
      <p:type>2</p:type>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>1</p:threads>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>1</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>2</p:subscriptor_id_ref>
      </p:subscriptors_ref>
    </p:mod>
    <p:mod>
      <p:type>3</p:type>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>4</p:threads>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>1</p:subscriptor_id_ref>
        <p:subscriptor_id_ref>2</p:subscriptor_id_ref>
      </p:subscriptors_ref>
    </p:mod>
  </p:mods>
</p:controller_adapter_v1>

=== SCADA-ITS/configscada/resources/master/adapters/controller/controller_adapter_v1_deprecated.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:controller_adapter_v1 name="" version="" xmlns:p="controller_adapter_v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="controller_adapter_v1 ../../../adapter-lib/src/main/resources/schemas/controller/controller_adapter_v1.xsd ">
  <p:subscriptors>
    <p:subscriptor>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:entity>GenericCommand</p:entity>
      <p:entity_pks>
		<p:entity_pk>type=1</p:entity_pk>
	  </p:entity_pks>
    </p:subscriptor>
  </p:subscriptors>
  <p:mods>
    <p:mod>
      <p:type>1</p:type>
      <p:id>1</p:id>
      <p:enabled>true</p:enabled>
      <p:threads>1</p:threads>
      <p:subscriptors_ref>
        <p:subscriptor_id_ref>1</p:subscriptor_id_ref>
      </p:subscriptors_ref>
      <p:mod_params>
		<p:mod_param_value>expire_time_s=3</p:mod_param_value>
	  </p:mod_params>
    </p:mod>
  </p:mods>
</p:controller_adapter_v1>
